sudo: false
language: rust
rust: 
  - nightly
  - stable
  - beta

<<<<<<< HEAD
=======
branches:
  except:
    - notes
    - developers-guides

>>>>>>> 3b81916b4ab22025133f15f819dbe33aad11c1f8
# Only while clippy is failing
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

os:
  - linux
  - osx

script:
  - cargo build --verbose
  - cargo test
  - cargo bench
