---
sudo: false
language: rust
rust:
  - nightly

os:
  - osx

branches:
  only:
    - master

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - cargo build
  - cargo test --features compositer_command
  - cargo test --features compositer_ffi
