language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly
os:
  - osx
matrix:
  include:
    - rust: nightly
      env: FEATURES=nightly

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/Library/Python/2.7/bin:$PATH
  - ls -R $HOME/
script:
  - |
      travis-cargo --only nightly build -- --features "nightly"
      travis-cargo --only nightly test -- --features "nightly"
      travis-cargo --only nightly doc -- --features "nightly"
after_success:
  - travis-cargo doc-uploada

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
