language: rust
rust:
  - nightly
matrix:
  include:
    - rust: nightly
      env: FEATURES=nightly
before_script:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - travis-cargo --only nightly build
  - travis-cargo --only nightly test
  - travis-cargo --only nightly doc
after_success:
  - travis-cargo doc-uploada
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
