[package]
name          = "neko"
version       = "0.0.1"
authors       = [
	"adjivas <adjivas@users.noreply.github.com>",
	"brezaire <voncay@users.noreply.github.com>",
	"flime <LinFeiLong@users.noreply.github.com>",
	"jpepin <limaconoob@users.noreply.github.com>"
]
<<<<<<< HEAD
=======
build         = "tango-build.rs"
>>>>>>> 3b81916b4ab22025133f15f819dbe33aad11c1f8
description   = ""
documentation = "https://adjivas.github.io/Neko/neko"
repository    = "https://github.com/adjivas/Neko.git"
readme        = "README.md"
keywords      = ["neko", "glyphArt"]
license       = "GPL-3.0"

[[bin]]
name          = "neko"
<<<<<<< HEAD
=======
path          = "src/main.rs"
>>>>>>> 3b81916b4ab22025133f15f819dbe33aad11c1f8
doc           = false

[lib]
name          = "neko"
<<<<<<< HEAD
=======
path          = "src/lib.rs"
>>>>>>> 3b81916b4ab22025133f15f819dbe33aad11c1f8
plugin        = true

[features]
default       = []
lints         = ["clippy", "nightly"]
nightly       = [] # for building with nightly and unstable features
unstable      = [] # for building with unstable features on stable Rust
debug         = [] # for building with debug messages
travis        = ["lints", "nightly"] # for building with travis-cargo

<<<<<<< HEAD
=======
[build-dependencies.tango]
git = "https://github.com/pnkfelix/tango"

>>>>>>> 3b81916b4ab22025133f15f819dbe33aad11c1f8
[dependencies.clippy]
version       = "*"
optional      = true
